name: ChatGPT Admin Agent
version: "0.1.7"
slug: chatgpt_admin_agent
description: Local admin bridge for Home Assistant configuration, registry and service operations
url: https://github.com/tfz02/home-assistant-chatgpt-admin-agent
arch:
  - amd64
startup: services
boot: auto
init: false
host_network: true
homeassistant_api: true
hassio_api: true
hassio_role: admin
map:
  - config:rw
  - share:rw
  - backup:rw
  - media:rw
  - ssl:rw
ports:
  8787/tcp: 8787
ports_description:
  8787/tcp: ChatGPT Admin Agent API
options:
  admin_token: "s9h34LVrR!yf8ees9h34LVrR!yf8ees9h34LVrR!yf8ees9h34LVrR!yf8ee"
  allow_shell: true
  allow_storage: true
  ngrok_enabled: true
  ngrok_authtoken: "3DGs2HKH7symGhYvckvG0h7xaPE_46hqK5jEaN2B7MGRL9eFf"
  ngrok_domain: "broadcast-gallstone-reforest.ngrok-free.dev"
schema:
  admin_token: str
  allow_shell: bool
  allow_storage: bool
  ngrok_enabled: bool
  ngrok_authtoken: str
  ngrok_domain: str?
